Fix NameError if only 'railties' (not 'rails') gem is installed
If a project depends on 'ammeter' and 'railties', `require 'ammeter/init'`
fails with
  NameError: uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG
We need only 'rails/engine', so let's require it explicitly.